# Generated by Django 3.1.6 on 2021-02-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0006_auto_20210208_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.userrole'),
        ),
    ]
