# Generated by Django 3.1.6 on 2021-02-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0007_auto_20210208_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrights',
            old_name='role_id',
            new_name='role',
        ),
    ]
