# Generated by Django 3.1.6 on 2021-02-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0008_auto_20210208_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrights',
            name='role',
            field=models.ForeignKey(default='Select Role', on_delete=django.db.models.deletion.CASCADE, to='UMS.userrole'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.ForeignKey(default='Select Role', on_delete=django.db.models.deletion.CASCADE, to='UMS.userrole'),
        ),
    ]
