# Generated by Django 3.1.6 on 2021-02-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(choices=[(1, 'admin'), (2, 'guest'), (3, 'user')], max_length=100),
        ),
    ]
