# Generated by Django 3.1.6 on 2021-02-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0002_auto_20210208_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_contact',
            field=models.IntegerField(),
        ),
    ]
