# Generated by Django 3.1.6 on 2021-02-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0003_auto_20210208_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('guest', 'guest'), ('user', 'user')], max_length=100),
        ),
    ]
