# Generated by Django 3.1.6 on 2021-02-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0004_auto_20210208_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(choices=[('admin', 1), ('guest', 2), ('user', 3)], max_length=100),
        ),
    ]
