# Generated by Django 3.1.6 on 2021-02-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0005_auto_20210208_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(choices=[(1, 'admin'), (2, 'guest'), (3, 'user')], max_length=100),
        ),
    ]
